name: it-jobs
services:
  backend:
    container_name: backend
    hostname: backend
    build: ../backend
    env_file: ../backend/env/.env
    volumes:
      - ../backend/data/app/logs:/logs
    networks:
      - it-jobs-network
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    logging:
      options:
        max-size: 10m

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    env_file: ../backend/env/.env
    volumes:
      - ../backend/data/app/mysql:/var/lib/mysql
    networks:
      - it-jobs-network
    ports:
      - "3306:3306"
    restart: always
    logging:
      options:
        max-size: 10m

  frontend:
    container_name: frontend
    hostname: frontend
    build: ../frontend
    networks:
      - it-jobs-network
    ports:
      - "3000:3000"
    restart: always
    logging:
      options:
        max-size: 10m

networks:
  it-jobs-network:
    external: true
